prod/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  resources :home, only: [:index]
  resources :productions
  get 'home/index'
  get '/productions/new', to: 'productions#new'
  get '/chat/home', to: 'chat#home'
end

prod/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

prod/app/models/production.rb
# frozen_string_literal: true

class Production < ApplicationRecord
  validates :name, :category, presence: true
end

prod/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

prod/app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def home
  end

  def index
  end
end

prod/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @productions = Production.all
    @productions = @productions.reverse
  end
end

prod/app/controllers/productions_controller.rb
# frozen_string_literal: true

class ProductionsController < ApplicationController
  before_action :set_production, only: %i[show edit update destroy]

  # GET /productions or /productions.json
  def index
    @productions = Production.all
  end

  # GET /productions/1 or /productions/1.json
  def show; end

  # GET /productions/new
  def new
    @production = Production.new
  end

  # GET /productions/1/edit
  def edit; end

  # POST /productions or /productions.json
  def create
    @production = Production.new(production_params)

    respond_to do |format|
      if @production.save
        format.html { redirect_to production_url(@production), notice: 'Production was successfully created.' }
        format.json { render :show, status: :created, location: @production }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @production.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productions/1 or /productions/1.json
  def update
    respond_to do |format|
      if @production.update(production_params)
        format.html { redirect_to production_url(@production), notice: 'Production was successfully updated.' }
        format.json { render :show, status: :ok, location: @production }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @production.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productions/1 or /productions/1.json
  def destroy
    @production.destroy

    respond_to do |format|
      format.html { redirect_to productions_url, notice: 'Production was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_production
    @production = Production.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def production_params
    params.require(:production).permit(:name, :category, :price, :comment)
  end
end

prod/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

prod/app/helpers/chat_helper.rb
module ChatHelper
end

prod/app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

prod/app/helpers/productions_helper.rb
# frozen_string_literal: true

module ProductionsHelper
end

prod/app/views/chat/home.html.erb
<h1>Messages</h1>
<div class="chat">
  <div class="p1 fukidashi">
    <p>テストメッセージです．</p>
    <p>こんにちは</p>
  </div>
  <div class="p2 fukidashi">
    <p>こんにちは！！</p>
  </div>
  <div class="p1 fukidashi">
    <p>この野菜の美味しい食べ方はありますか？？</p>
  </div>
</div>
<p>
<div class="new-message">
<%= form_with do |form| %>
  メッセージを送信する
<%= form.text_field :query %>
<% end %>
</p>
</div>

prod/app/views/home/index.html.erb
<!--- <h1>テストアプリ</h1> --->
<h2>新着の食材一覧</h2>
<body>
    <div class="board">
    <% cnt = 0 %>
    <% @productions.each do |production| %>
        <% cnt += 1 %>
        <% if cnt == 10 %>
            <% break %>
        <% end %>
        <div class="box">
        食材名: <%= production.name %><br>
        <%= image_tag "#{production.category}.jpeg", class:'image' %>
        <br>
        カテゴリ: <%= production.category %><br>
        値段: <%= production.price %> 円<br>
        コメント: <%= production.comment %><br>
            <div class="message_creater">
                <%= link_to "生産者の方へメッセージを送る", "chat/home" %> <br>
            </div>
        </div>
    <% end %>
    </div>
    <div class = "create-product">
    <%= link_to "新規作成", new_production_path %>
    </div>
</body>

prod/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "クックパッドインターンシップ課題" %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header>
      <div class="container navbar-brand">
        <%= link_to "Cookpad Intern App", root_path %>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

prod/app/views/productions/_form.html.erb
<%= form_with(model: production) do |form| %>
  <% if production.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(production.errors.count, "error") %> prohibited this production from being saved:</h2>

      <ul>
        <% production.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_field :comment %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

prod/app/views/productions/_production.html.erb
<div id="<%= dom_id production %>">
  <p>
    <strong>Name:</strong>
    <%= production.name %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= production.category %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= production.price %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= production.comment %>
  </p>

</div>

prod/app/views/productions/edit.html.erb
<h1>Editing production</h1>

<%= render "form", production: @production %>

<br>

<div>
  <%= link_to "Show this production", @production %> |
  <%= link_to "Back to productions", productions_path %>
</div>

prod/app/views/productions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Productions</h1>

<div id="productions">
  <% @productions.each do |production| %>
    <%= render production %>
    <p>
      <%= link_to "Show this production", production %>
    </p>
  <% end %>
</div>

<%= link_to "New production", new_production_path %>

prod/app/views/productions/new.html.erb
<h1>New production</h1>

<%= render "form", production: @production %>

<br>

<div>
  <%= link_to "Back to productions", productions_path %>
</div>

prod/app/views/productions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @production %>

<div>
  <%= link_to "Edit this production", edit_production_path(@production) %> |
  <%= link_to "Back to productions", productions_path %>

  <%= button_to "Destroy this production", @production, method: :delete %>
</div>